### ISSUE TITLE
failed to download - tutorial error

### ISSUE THREAD

**Issue by vodelerk** [hashicorp/learn-terraform-kubernetes-operator#2]
I'm trying to reproduce this tutorial ( https://learn.hashicorp.com/tutorials/terraform/kubernetes-operator?in=terraform/cloud ) , but I'm getting this error after terraform apply in the "Deploy operator" section.

`
Enter a value: yes

helm_release.operator: Creating...
╷
│ Error: failed to download "https://helm.releases.hashicorp.com/terraform-1.0.0.tgz" (hint: running `helm repo update` may help)
│
│   with helm_release.operator,
│   on main.tf line 84, in resource "helm_release" "operator":
│   84: resource "helm_release" "operator" {
`

when I clicked on the link of the error it let me download that file, but if I visit https://helm.releases.hashicorp.com/, I don't see that file to download, but I do see the helm chart for vault and consul.
I'm on windows 10.

any advice?
thanks.

**Comment by im2nguyen** [comment]
Hi @vodelerk! Have you tried running `helm repo update`? that _should_ fix your problem

1. Add hashicorp helm repo
    ```
    $ helm repo add hashicorp https://helm.releases.hashicorp.com
    "hashicorp" already exists with the same configuration, skipping
    ```

1. Update local hashicorp helm repo 
    ```
    $ helm repo update
    Hang tight while we grab the latest from your chart repositories...
    ...Successfully got an update from the "hashicorp" chart repository
    Update Complete. ⎈Happy Helming!⎈
    ```

1. Verify terraform-helm chart is present
      ```
      $ helm search repo hashicorp/terraform
      NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                       
      hashicorp/terraform     1.0.0                           Install and configure Terraform Cloud Operator ...
      ```

**Comment by vodelerk** [comment]
I was missing helm locally, I had to "choco install kubernetes-helm" and after that, "helm repo update". Everything works smoothly! Thank you very much!
